// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyslIesLns_dWzaql5Uh5348g22-7j5CE',
    appId: '1:125710236968:android:7eee70b0f38a745f56241d',
    messagingSenderId: '125710236968',
    projectId: 'papsnpops',
    storageBucket: 'papsnpops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-wWaG9r5EW6FzLW_NK3jegnySVlgJ2s',
    appId: '1:125710236968:ios:2659b5605cd854ea56241d',
    messagingSenderId: '125710236968',
    projectId: 'papsnpops',
    storageBucket: 'papsnpops.firebasestorage.app',
    iosBundleId: 'com.wolfeleo2.papsNPops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-wWaG9r5EW6FzLW_NK3jegnySVlgJ2s',
    appId: '1:125710236968:ios:2659b5605cd854ea56241d',
    messagingSenderId: '125710236968',
    projectId: 'papsnpops',
    storageBucket: 'papsnpops.firebasestorage.app',
    iosBundleId: 'com.wolfeleo2.papsNPops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEoUyIfY63KZQmStpi-M2imnRc9LzzvjQ',
    appId: '1:125710236968:web:a53bafa84f2cd34056241d',
    messagingSenderId: '125710236968',
    projectId: 'papsnpops',
    authDomain: 'papsnpops.firebaseapp.com',
    storageBucket: 'papsnpops.firebasestorage.app',
    measurementId: 'G-VXQ1PMQDM2',
  );
}
